name: tests

on:
  push:
  pull_request:
    branches: [ $default-branch ]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: latest

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Lint
        run: pnpm lint

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: latest

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm run build

  mugshot:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: latest

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Test
        run: pnpm test
        working-directory: packages/mugshot

      - name: Coverage
        uses: codecov/codecov-action@v3
        with:
          flags: mugshot

  webdriverio:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        browser: ['chrome', 'firefox']

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: latest

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Test
        run: pnpm test
        env:
          BROWSER: ${{ matrix.browser }}
        working-directory: packages/webdriverio

      - name: Coverage
        uses: codecov/codecov-action@v3
        with:
          flags: webdriverio, ${{ matrix.browser }}

  puppeteer:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        version: [ 8, 9, "installed" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: latest

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Version
        if: ${{ matrix.version != 'installed' }}
        run: pnpm add -D puppeteer@${{ matrix.version }}
        working-directory: packages/puppeteer

      - name: Test
        run: pnpm test
        working-directory: packages/puppeteer

      - name: Coverage
        uses: codecov/codecov-action@v3
        with:
          flags: puppeteer, ${{ matrix.version }}

  playwright:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        browser: [ 'chromium', 'firefox' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.1
        with:
          version: latest

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Test
        run: pnpm test
        env:
          BROWSER: ${{ matrix.browser }}
        working-directory: packages/playwright

      - name: Coverage
        uses: codecov/codecov-action@v3
        with:
          flags: playwright, ${{ matrix.browser }}
